#pragma once

/**
 * @file
 * Stub related facilities
 *
 * Helpers for the content autogenerated by the @c generate-stubs.cmake script
 * using the @c winmm.txt file, which contains all the function exports of the
 * Windows provided @c WINMM.DLL. This text file can be generated using either
 * the AWK script or its C reimplementation found in the @c tools directory of
 * the project.
 */

/**
 * @defgroup stubs Stub management
 *
 * Provides the functions to initialize and destroy the stub functionality.
 * @{
 */

/**
 * Library handle of @c WINMM.DLL
 */
extern void* winmm_handle;

/**
 * Loads function pointers to @c WINMM.DLL
 *
 * @return 0 if successful, non-zero if an error occured
 *
 * @details The implementation of this function is autogenerated by the @c
 * generate-stubs.cmake script. For use by ::stubs_ctor.
 */
int stubs_load(void);

/**
 * Initializes stub functionality
 *
 * @return 0 if successful, non-zero if an error occured
 */
int stubs_ctor(void);

/**
 * Destroys resources related to stub functionality
 *
 * @return 0 if successful, non-zero if an error occured
 */
int stubs_dtor(void);

/** @} */
