name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

env:
  VCPKG_COMMIT: "16ee2ecb31788c336ace8bb14c21801efb6836e4"

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-14 -P cmake/lint.cmake

  clang:
    needs: [lint]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: ${{ env.VCPKG_COMMIT }}
        cache-version: clang

    - name: Setup toolchain file
      run: cmake -P .github/vcpkg/toolchain.cmake

    - name: Configure
      run: cmake --preset=ci-clang

    - name: Build
      run: cmake --build build -j 2

    - name: Install
      run: cmake --install build --prefix prefix

  msvc:
    needs: [lint]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: ${{ env.VCPKG_COMMIT }}
        cache-version: msvc

    - name: Configure
      run: cmake --preset=ci-windows

    - name: Build
      run: cmake --build build -j 2

    - name: Install
      run: cmake --install build --prefix prefix

  docs:
    # Deploy docs only when builds succeed
    needs: [msvc, clang]

    runs-on: ubuntu-22.04

    if: github.ref == 'refs/heads/master'
      && github.event_name == 'push'
      && github.repository_owner == 'friendlyanon'

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen graphviz -q -y

    - name: Build docs
      working-directory: docs
      run: |
        printf %s\\n "OUTPUT_DIRECTORY = $PWD" >> Doxyfile
        (cd ../source; doxygen ../docs/Doxyfile)

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
