name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-14 -P cmake/lint.cmake

  build:
    needs: [lint]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Install vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: "16ee2ecb31788c336ace8bb14c21801efb6836e4"

    - name: Configure
      run: cmake --preset=ci-windows

    - name: Build
      run: cmake --build build -j 2

    - name: Install
      run: cmake --install build --prefix prefix
